version: '2'
services:
  db:
    command: --character-set-server=utf8mb4
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dos_dev
      MYSQL_USER: planx
      MYSQL_PASSWORD: planx

  redis:
    image: redis:3.2.1-alpine
    ports:
    - 6379:6379

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      FLASK_ENV: development
      REDIS_URL: redis://redis:6379/0
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://planx:planx@db/dos_dev
